steps:

  - name: 'node'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        make lint-frontend
    dir: 'agent-app'
    id: 'frontend-lint-check'
    waitFor: ['-']

options:
  logging: CLOUD_LOGGING_ONLY
