name: PR Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Python Project using uv
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the code
        run: |
          cd agent-app
          make checks-github

      - name: Lint the code
        run: |
          make install
          cd agent-app/app
          pip install pylint
          find . -path './.venv' -prune -o -name "*.py" -type f -print0 | xargs -0 pylint --ignore-paths='utils/.*' --disable=unexpected-keyword-arg,missing-kwoa

      
