name: PR Build Check

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Python Project using uv
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the code
        run: |
          cd agent-app
          make checks-github

      
